project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    df-print: paged
    code-fold: true
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  agu-pdf: default



