project:
  type: book

book:
  title: "L'assurance-maladie obligatoire suisse dans l'impasse. Une analyse du compromis socio-politique derrière la Loi fédérale sur l’assurance-maladie (LAMal)"
  subtitle: "Annexe"
  author: "Celâl Güney"
  date: "27.02.2026"
  chapters:
    - index.qmd


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
